import type { Client, User, Document, ValidationItem } from './types'
import { VALIDATION_CHECKLIST } from './constants'

// Helper to create validation checklist
const createChecklist = (checkedIds: string[] = []): ValidationItem[] => {
  return VALIDATION_CHECKLIST.map(item => ({
    id: item.id,
    label: item.label,
    checked: checkedIds.includes(item.id),
    nota: '',
  }))
}

// Mock Users
export const mockUsers: User[] = [
  {
    id: 'user-1',
    nombre: 'Gonzalo Herrera',
    email: 'gonzalo@worcap.com',
    rol: 'oficial',
    sucursal: 'Palermo',
  },
  {
    id: 'user-2',
    nombre: 'Laura Gómez',
    email: 'laura@worcap.com',
    rol: 'analista',
    equipo: 'Créditos',
  },
  {
    id: 'user-3',
    nombre: 'Martín Ferreyra',
    email: 'martin@distribuidoradelnorte.com',
    rol: 'cliente',
  },
]

// Helper to create document with status
const createDoc = (id: string, nombre: string, estado: Document['estado'], obligatorio = true): Document => ({
  id,
  nombre,
  estado,
  obligatorio,
  fechaCarga: estado !== 'pendiente' ? new Date(2024, 2, 15) : undefined,
})

// Mock Clients
export const mockClients: Client[] = [
  {
    id: 'client-1',
    razonSocial: 'Distribuidora Del Norte SRL',
    cuit: '30-71234567-8',
    tipo: 'SRL',
    sector: 'Comercio mayorista',
    estado: 'enRevision',
    completitud: 75,
    montoSolicitado: 12500000,
    plazo: 24,
    analistaAsignado: 'Laura Gómez',
    email: 'contacto@distribuidoradelnorte.com',
    telefono: '+54 9 11 4567-8901',
    domicilio: 'Av. Corrientes 1234',
    ciudad: 'Buenos Aires',
    provincia: 'CABA',
    codigoPostal: '1043',
    actividad: 'Comercio mayorista',
    fechaInicioActividad: new Date(2015, 5, 1),
    facturacionAnual: 45000000,
    socios: [
      { id: 'socio-1', nombre: 'Martín Ferreyra', dni: '28.456.789', participacion: 60, firmaAutorizada: true },
      { id: 'socio-2', nombre: 'Claudia Vidal', dni: '30.123.456', participacion: 40, firmaAutorizada: true },
    ],
    documentos: [
      createDoc('estatuto', 'Estatuto social con últimas modificaciones', 'aprobado'),
      createDoc('dni_socios', 'DNI de cada socio', 'aprobado'),
      createDoc('balance_1', 'Estado contable certificado 2023', 'enRevision'),
      createDoc('balance_2', 'Estado contable certificado 2022', 'pendiente'),
      createDoc('acta_autoridades', 'Acta de designación de autoridades', 'subido'),
      createDoc('ddjj_ganancias_1', 'Declaración jurada de ganancias 2023', 'subido'),
      createDoc('ddjj_ganancias_2', 'Declaración jurada de ganancias 2022', 'pendiente'),
      createDoc('ddjj_ganancias_3', 'Declaración jurada de ganancias 2021', 'pendiente'),
      createDoc('composicion_accionaria', 'Composición accionaria certificada', 'subido'),
      createDoc('extracto_bancario', 'Extracto bancario últimos 6 meses', 'aprobado'),
    ],
    fechaCreacion: new Date(2024, 1, 10),
    historial: [
      { id: 'h1', fecha: new Date(2024, 1, 10), accion: 'Solicitud creada', usuario: 'Gonzalo Herrera' },
      { id: 'h2', fecha: new Date(2024, 1, 12), accion: 'Documentos cargados', usuario: 'Martín Ferreyra', detalle: '5 documentos' },
      { id: 'h3', fecha: new Date(2024, 1, 15), accion: 'Asignado a analista', usuario: 'Sistema', detalle: 'Laura Gómez' },
      { id: 'h4', fecha: new Date(2024, 2, 1), accion: 'Documentos aprobados', usuario: 'Laura Gómez', detalle: 'Estatuto, DNI socios' },
    ],
    notasInternas: 'Cliente con buen historial crediticio. Verificar último balance.',
    checklist: createChecklist(['identidad', 'cuit_activo', 'sin_deudas']),
    escenarios: {
      conservador: { ingresos: 40000000, egresos: 35000000, ebitda: 5000000, ratioEndeudamiento: 0.45, coberturaDeuda: 1.2, probabilidadDefault: 8, calificacion: 'BBB' },
      base: { ingresos: 45000000, egresos: 36000000, ebitda: 9000000, ratioEndeudamiento: 0.35, coberturaDeuda: 2.1, probabilidadDefault: 4, calificacion: 'A' },
      agresivo: { ingresos: 52000000, egresos: 38000000, ebitda: 14000000, ratioEndeudamiento: 0.25, coberturaDeuda: 3.2, probabilidadDefault: 2, calificacion: 'AA' },
    },
    diasEnCola: 5,
  },
  {
    id: 'client-2',
    razonSocial: 'Agropecuaria San Marcos SA',
    cuit: '30-68901234-5',
    tipo: 'SA',
    sector: 'Agricultura',
    estado: 'pendienteDocumentos',
    completitud: 40,
    montoSolicitado: 28000000,
    plazo: 36,
    analistaAsignado: 'Laura Gómez',
    email: 'admin@sanmarcos.com.ar',
    telefono: '+54 9 351 456-7890',
    domicilio: 'Ruta Nacional 9 Km 45',
    ciudad: 'Jesús María',
    provincia: 'Córdoba',
    codigoPostal: '5220',
    actividad: 'Agricultura',
    fechaInicioActividad: new Date(2008, 3, 15),
    facturacionAnual: 85000000,
    directores: [
      { id: 'dir-1', nombre: 'Ing. Roberto Ibáñez', cargo: 'Presidente', dni: '22.345.678', participacion: 55 },
      { id: 'dir-2', nombre: 'Lic. Florencia Paz', cargo: 'Directora', dni: '29.876.543', participacion: 45 },
    ],
    documentos: [
      createDoc('estatuto', 'Estatuto social', 'aprobado'),
      createDoc('acta_directorio', 'Acta de directorio vigente', 'subido'),
      createDoc('balance_1', 'Estado contable certificado con dictamen 2023', 'pendiente'),
      createDoc('balance_2', 'Estado contable certificado con dictamen 2022', 'pendiente'),
      createDoc('balance_3', 'Estado contable certificado con dictamen 2021', 'pendiente'),
      createDoc('ddjj_ganancias_1', 'Declaración jurada de ganancias 2023', 'pendiente'),
      createDoc('ddjj_ganancias_2', 'Declaración jurada de ganancias 2022', 'pendiente'),
      createDoc('ddjj_ganancias_3', 'Declaración jurada de ganancias 2021', 'pendiente'),
      createDoc('dni_directores', 'DNI de directores y accionistas mayoritarios', 'subido'),
      createDoc('nomina_accionistas', 'Nómina de accionistas certificada', 'pendiente'),
      createDoc('extracto_bancario', 'Extracto bancario últimos 6 meses', 'pendiente'),
    ],
    fechaCreacion: new Date(2024, 2, 5),
    historial: [
      { id: 'h1', fecha: new Date(2024, 2, 5), accion: 'Solicitud creada', usuario: 'Gonzalo Herrera' },
      { id: 'h2', fecha: new Date(2024, 2, 8), accion: 'Documentos cargados', usuario: 'Roberto Ibáñez', detalle: '3 documentos' },
    ],
    checklist: createChecklist(['identidad']),
    diasEnCola: 12,
  },
  {
    id: 'client-3',
    razonSocial: 'Tech Solutions',
    cuit: '20-35678901-2',
    tipo: 'RI',
    sector: 'Servicios informáticos',
    estado: 'aprobado',
    completitud: 100,
    montoSolicitado: 4800000,
    montoAprobado: 4800000,
    plazo: 12,
    analistaAsignado: 'Laura Gómez',
    email: 'diego@techsolutions.com.ar',
    telefono: '+54 9 11 5678-1234',
    domicilio: 'Av. del Libertador 5678, Piso 8',
    ciudad: 'Buenos Aires',
    provincia: 'CABA',
    codigoPostal: '1426',
    actividad: 'Servicios informáticos',
    fechaInicioActividad: new Date(2019, 8, 1),
    facturacionAnual: 18000000,
    tieneEmpleados: true,
    cantidadEmpleados: 12,
    documentos: [
      createDoc('dni', 'DNI titular', 'aprobado'),
      createDoc('constancia_afip', 'Constancia de inscripción AFIP', 'aprobado'),
      createDoc('balance_1', 'Estado contable certificado (último)', 'aprobado'),
      createDoc('balance_2', 'Estado contable certificado (anterior)', 'aprobado'),
      createDoc('ddjj_ganancias_1', 'Declaración jurada de ganancias (última)', 'aprobado'),
      createDoc('ddjj_ganancias_2', 'Declaración jurada de ganancias (anterior)', 'aprobado'),
      createDoc('extracto_bancario', 'Extracto bancario últimos 3 meses', 'aprobado'),
    ],
    fechaCreacion: new Date(2024, 0, 15),
    historial: [
      { id: 'h1', fecha: new Date(2024, 0, 15), accion: 'Solicitud creada', usuario: 'Gonzalo Herrera' },
      { id: 'h2', fecha: new Date(2024, 0, 20), accion: 'Documentación completa', usuario: 'Diego Morales' },
      { id: 'h3', fecha: new Date(2024, 0, 25), accion: 'Solicitud aprobada', usuario: 'Laura Gómez' },
    ],
    checklist: createChecklist(['identidad', 'cuit_activo', 'sin_deudas', 'dictamen_auditor', 'docs_vigentes', 'actividad_consistente', 'garantias']),
    escenarios: {
      conservador: { ingresos: 16000000, egresos: 12000000, ebitda: 4000000, ratioEndeudamiento: 0.30, coberturaDeuda: 2.5, probabilidadDefault: 3, calificacion: 'A' },
      base: { ingresos: 18000000, egresos: 12500000, ebitda: 5500000, ratioEndeudamiento: 0.22, coberturaDeuda: 3.4, probabilidadDefault: 2, calificacion: 'AA' },
      agresivo: { ingresos: 22000000, egresos: 14000000, ebitda: 8000000, ratioEndeudamiento: 0.15, coberturaDeuda: 5.0, probabilidadDefault: 1, calificacion: 'AAA' },
    },
    diasEnCola: 0,
  },
  {
    id: 'client-4',
    razonSocial: 'Cooperativa de Trabajo Unión Gráfica',
    cuit: '30-59012345-6',
    tipo: 'cooperativa',
    sector: 'Imprenta / editorial',
    estado: 'incompleto',
    completitud: 25,
    montoSolicitado: 7200000,
    plazo: 18,
    email: 'info@uniongrafica.coop',
    telefono: '+54 9 11 3456-7890',
    domicilio: 'Av. Boedo 1234',
    ciudad: 'Buenos Aires',
    provincia: 'CABA',
    codigoPostal: '1239',
    actividad: 'Imprenta / editorial',
    fechaInicioActividad: new Date(2012, 6, 1),
    facturacionAnual: 22000000,
    numeroMatricula: 'INAES-45678',
    autoridades: [
      { id: 'aut-1', nombre: 'Ana Cáceres', cargo: 'Presidenta', periodo: '2023-2025' },
      { id: 'aut-2', nombre: 'Pablo Ruiz', cargo: 'Secretario', periodo: '2023-2025' },
    ],
    documentos: [
      createDoc('estatuto', 'Estatuto y reglamento interno', 'subido'),
      createDoc('acta_autoridades', 'Acta de autoridades vigentes', 'pendiente'),
      createDoc('matricula_inaes', 'Matrícula cooperativa (INAES)', 'pendiente'),
      createDoc('balance_1', 'Estado contable 2023', 'pendiente'),
      createDoc('balance_2', 'Estado contable 2022', 'pendiente'),
      createDoc('dni_autoridades', 'DNI de autoridades', 'pendiente'),
    ],
    fechaCreacion: new Date(2024, 2, 20),
    historial: [
      { id: 'h1', fecha: new Date(2024, 2, 20), accion: 'Solicitud creada', usuario: 'Gonzalo Herrera' },
    ],
    checklist: createChecklist([]),
    diasEnCola: 8,
  },
  {
    id: 'client-5',
    razonSocial: 'Panadería Artesanal',
    cuit: '27-41234567-8',
    tipo: 'monotributo',
    sector: 'Alimentos y bebidas',
    estado: 'pendienteDocumentos',
    completitud: 60,
    montoSolicitado: 900000,
    plazo: 6,
    email: 'valeria@panaderiartesanal.com',
    telefono: '+54 9 11 2345-6789',
    domicilio: 'Calle Mitre 456',
    ciudad: 'Morón',
    provincia: 'Buenos Aires',
    codigoPostal: '1708',
    actividad: 'Alimentos y bebidas',
    fechaInicioActividad: new Date(2020, 2, 1),
    facturacionAnual: 4200000,
    categoriaMono: 'H',
    documentos: [
      createDoc('dni', 'DNI titular (frente y dorso)', 'aprobado'),
      createDoc('constancia_afip', 'Constancia de inscripción AFIP', 'aprobado'),
      createDoc('recibo_monotributo', 'Último recibo/comprobante de pago monotributo', 'subido'),
      createDoc('extracto_bancario', 'Extracto bancario últimos 3 meses', 'pendiente'),
    ],
    fechaCreacion: new Date(2024, 2, 25),
    historial: [
      { id: 'h1', fecha: new Date(2024, 2, 25), accion: 'Solicitud creada', usuario: 'Gonzalo Herrera' },
      { id: 'h2', fecha: new Date(2024, 2, 27), accion: 'Documentos cargados', usuario: 'Valeria Torres', detalle: '3 documentos' },
    ],
    checklist: createChecklist(['identidad', 'cuit_activo']),
    diasEnCola: 3,
  },
  {
    id: 'client-6',
    razonSocial: 'Servicios Financieros del Río SA',
    cuit: '30-72345678-9',
    tipo: 'entidadFinanciera',
    sector: 'Finanzas',
    estado: 'enRevision',
    completitud: 85,
    montoSolicitado: 85000000,
    plazo: 48,
    analistaAsignado: 'Laura Gómez',
    email: 'institucional@sfrio.com.ar',
    telefono: '+54 11 4567-8900',
    domicilio: 'Av. Leandro N. Alem 456, Piso 15',
    ciudad: 'Buenos Aires',
    provincia: 'CABA',
    codigoPostal: '1001',
    actividad: 'Finanzas',
    fechaInicioActividad: new Date(2005, 0, 1),
    facturacionAnual: 350000000,
    autorizacionBCRA: 'BCRA-2005-4567',
    tipoEntidad: 'Compañía financiera',
    capitalMinimo: 500000000,
    documentos: [
      createDoc('autorizacion_bcra', 'Autorización BCRA', 'aprobado'),
      createDoc('estatuto', 'Estatuto social', 'aprobado'),
      createDoc('memoria_balance', 'Memoria y balance anual', 'enRevision'),
      createDoc('informe_auditoria', 'Informe de auditoría externa', 'subido'),
      createDoc('integracion_capital', 'Integración de capital regulatorio', 'subido'),
    ],
    fechaCreacion: new Date(2024, 1, 28),
    historial: [
      { id: 'h1', fecha: new Date(2024, 1, 28), accion: 'Solicitud creada', usuario: 'Gonzalo Herrera' },
      { id: 'h2', fecha: new Date(2024, 2, 2), accion: 'Documentación cargada', usuario: 'Admin SFRío' },
      { id: 'h3', fecha: new Date(2024, 2, 10), accion: 'Asignado a analista', usuario: 'Sistema', detalle: 'Laura Gómez' },
    ],
    checklist: createChecklist(['identidad', 'cuit_activo', 'sin_deudas', 'dictamen_auditor', 'docs_vigentes']),
    escenarios: {
      conservador: { ingresos: 320000000, egresos: 280000000, ebitda: 40000000, ratioEndeudamiento: 0.55, coberturaDeuda: 1.5, probabilidadDefault: 6, calificacion: 'BBB' },
      base: { ingresos: 350000000, egresos: 290000000, ebitda: 60000000, ratioEndeudamiento: 0.45, coberturaDeuda: 2.2, probabilidadDefault: 4, calificacion: 'A' },
      agresivo: { ingresos: 400000000, egresos: 310000000, ebitda: 90000000, ratioEndeudamiento: 0.35, coberturaDeuda: 3.3, probabilidadDefault: 2, calificacion: 'AA' },
    },
    diasEnCola: 7,
  },
]

// Get current user based on role
export const getUserByRole = (role: 'oficial' | 'analista' | 'cliente'): User => {
  return mockUsers.find(u => u.rol === role) || mockUsers[0]
}

// Generate expediente number
export const generateExpediente = (): string => {
  const year = new Date().getFullYear()
  const num = Math.floor(Math.random() * 9000) + 1000
  return `WCP-${year}-${num}`
}
